#!/bin/bash
# Get your valid Roboflow API key

echo "=================================================="
echo "How to Get Your Roboflow API Key"
echo "=================================================="
echo ""
echo "Follow these steps:"
echo ""
echo "1. Go to: https://app.roboflow.com/login"
echo "   - Sign up for a FREE account (no credit card needed)"
echo "   - Or log in if you already have an account"
echo ""
echo "2. After logging in, click your profile picture (top right)"
echo ""
echo "3. Click 'Settings' or go directly to:"
echo "   https://app.roboflow.com/settings/api"
echo ""
echo "4. Under 'Roboflow API', you'll see your Private API Key"
echo "   - Click 'Copy' to copy it"
echo ""
echo "5. Set it as an environment variable:"
echo "   export ROBOFLOW_API_KEY='your_actual_key_here'"
echo ""
echo "6. Then run the download script again:"
echo "   python3 download_mineral_model.py"
echo ""
echo "=================================================="
echo "Alternative: Manual Download (No API Key Needed)"
echo "=================================================="
echo ""
echo "You can download the dataset manually:"
echo ""
echo "1. Visit: https://universe.roboflow.com/mineraldetectionyolo/mineral-c42yg"
echo ""
echo "2. Click 'Download Dataset' button"
echo ""
echo "3. Select format: 'YOLOv11 PyTorch'"
echo ""
echo "4. Click 'Continue' then 'Download'"
echo ""
echo "5. Extract the downloaded ZIP file to:"
echo "   /media/monders/Files/robotics/mines/ros2_ws/mineral_dataset/"
echo ""
echo "6. The folder should contain:"
echo "   - train/    (training images)"
echo "   - valid/    (validation images)"
echo "   - test/     (test images)"
echo "   - data.yaml (dataset configuration)"
echo ""
echo "7. Then you can train:"
echo "   yolo train data=mineral_dataset/data.yaml model=yolo11n.pt epochs=100"
echo ""
echo "=================================================="
